version: '3.5'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - '4200:4200'
    command: /bin/bash -c "npm install &&  ng serve --host 0.0.0.0"
 